### ISSUE TITLE
Link the documentation

### ISSUE THREAD

**Issue by rrjanbiah** [chung-leong/acrostix#1]
It is such a nice library that you can use existing PDF files as a template to generate nice looking PDF files. I vaguely remember that you kept the documentation in some blogspot site and that is now not searchable. Please link that in the README. 

BTW, I found this Wiki https://code.google.com/archive/p/acrostix/wikis/FunctionReference.wiki

**Comment by chung-leong** [comment]
I found the blog on Wayback Machine: https://web.archive.org/web/20140519132838/http://chernyshevsky.blogspot.com/. I'll update the doc here when I get a chance.

**Comment by chung-leong** [comment]
Copied contents from old blog posts into README.
